### ISSUE TITLE
The av insights module uses "unload" event

### ISSUE THREAD

**Issue by romainst** [at-internet/piano-analytics-js#3]
The unload event is more and more seen as a bad practice in terms of performance by browsers and search engines.
Could you please use either "beforeunload" or "pagehide" to avoid triggering errors in lighthouse reports?

https://github.com/at-internet/piano-analytics-js/blob/412fd92b217fdfb8587acf1ba3ac5f8cfca2e1f8/src/business/avinsights.js#L325C45-L325C45

From Lighthouse report:
The `unload` event does not fire reliably and listening for it can prevent browser optimizations like the Back-Forward Cache. Use `pagehide` or `visibilitychange` events instead. [Learn more about unload event listeners](https://web.dev/bfcache/?utm_source=lighthouse&utm_medium=lr#never-use-the-unload-event)

**Comment by BenDz** [comment]
Hi @romainst 
Thanks for the heads up, we'll take a look at it.

**Comment by dumbNickname** [comment]
While checking existing issues I noticed that this issue seems to be outdated. Since this commit: https://github.com/at-internet/piano-analytics-js/commit/abecfc4bfbbbc91f1199348cdd98a2b5450bfc58 it looks like pagehide event is being used.

**Comment by BenDz** [comment]
Thanks @dumbNickname, totally forgot to get back in this issue!
