### ISSUE TITLE
Events from Android are being excluded on Piano

### ISSUE THREAD

**Issue by StuartPyper** [at-internet/piano-analytics-js#4]
We have set up piano-analytics-js for events on our react app and we are able to see custom events and properties being sent to Piano from iOS devices no problem. For some reason when we send the _exact_ same events from an Android device, I can see that Piano is lumping them all in the 'Excluded events' results for some reason. 

Does anyone know why this might be? If the events are reaching Piano then why are they being excluded?

Note: We have no exclusion rules set up at the Piano side and the same thing is happening for basic 'page.display' events also. 
I also checked the pianoAnalytics.privacy.getMode() and for both devices it comes back as 'optin'.

**Comment by BenDz** [comment]
Hi @StuartPyper 
This can happen for a number of reasons.
Please open a support request at support@piano.io and our consultants will be happy to track down what's wrong with your tagging.

**Comment by StuartPyper** [comment]
Thank you.

Piano support have confirmed that it was happening because their system identified the user agent used by our Android application as a bot for some reason. They have asked us to set a custom user agent. 
Hope that helps anyone else having this issue.
