### ISSUE TITLE
JSON parse issue on js content

### ISSUE THREAD

**Issue by MaxDesplanches** [at-internet/piano-analytics-js#5]
Hello,

I am including piano analytics js with CDN url for my script, but I got error on eval only on firefox. I know eval is not a best practice, but I want to use it for now, it works well on chrome and safari. Here is the error from my environment and the line executed:

![Screenshot 2024-07-26 at 14 47 34](https://github.com/user-attachments/assets/5e01b400-9fcd-43bc-b141-24ac77b0acaa)

![Screenshot 2024-07-26 at 14 48 00](https://github.com/user-attachments/assets/965f9d88-c1cc-4267-8fa7-b557d6646ad6)

Here is the code imported executed with eval, did you had similar issue please ? On firefox:

[pianoAnalytics.txt](https://github.com/user-attachments/files/16392088/pianoAnalytics.txt)

Did I miss something ? The file is maybe not correct ?

Thanks !
Max.

**Comment by BenDz** [comment]
Hello @MaxDesplanches 

Could you please contact our support center support@piano.io, or directly from our interface, with more details on the context.
Also, please mention if it worked with previous versions of our library.

Thank you
Ben
