### ISSUE TITLE
AV insights do not support SPAs properly - heartbeat event not stopped

### ISSUE THREAD

**Issue by dumbNickname** [at-internet/piano-analytics-js#6]
It looks like the library is intended only for server side rendered pages without videos being dynamically rendered / disposed.

After calling `setPlaybackSpeed` a set of timers is established for a heartbeat functionality. Those timers are being stopped in multiple scenarios, including videos being paused, stopped or on pagehide event taking place. Unfortunately in Single Page Apps (or apps that at least partially implement browser based routing) none of those events / calls will happen e.g. when navigating away from the page that plays the current video. It means that when navigating from page A to page B takes place (via browser based routing) while some video is playing, heartbeat events are still being sent for videos on page A, despite not being visible anymore on the page B. This impacts tracking metrics and builds a falsy impression of what, when and how long is being played. 

Unfortunately the API surface does not expose a possibility to stop those timers when e.g. disposing the video (we use video.js as our main library, so such callbacks are rather easy to work with). The timers are hidden in code via closures, so we cannot manually call the code:

```
            _timers.stopHeartbeatTimer(false);
            _timers.stopHeartbeatTimer(true);
```

We could call one of the API methods like `playbackStopped` to solve the heartbeat issue (and that is the most likely temporary solution we will go with), but then we still end up with an additional, artificial event that is not really triggered by the user.  

Would it be possible to add a method available in the public API surface intended to just stop those timers / do some session cleanup like when video is stopped, but without sending the additional tracking event?

**Comment by BenDz** [comment]
Hi @dumbNickname 
We just published v6.15.0 with a new method `playbackKill` to achieve this.
